version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    open-pull-requests-limit: 5
    reviewers:
      - MM25Zamanian
    schedule:
      interval: daily
    labels:
      - ci
      - priority-low
      - maintenance

  - package-ecosystem: npm
    directory: /
    versioning-strategy: increase
    open-pull-requests-limit: 5
    reviewers:
      - MM25Zamanian
    schedule:
      interval: daily
    labels:
      - dependencies
      - ci
      - priority-low
      - maintenance
