@apiUrl = https://api.hami-app.ir/v0
@accessToken = YOUR_SECRET_TOKEN
@userAdminToken = g6y6OMr9DuRYHpoAyH2iJ-WddGUKqE-UTsym013-o8I
@adminToken = ADMIN_SECRET_TOKEN

### Home
GET {{apiUrl}}/

### Sign In
POST {{apiUrl}}/sign-in/
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "data": {
    "phoneNumber": "09155595488",
    "password": "zamanian.1384"
  }
}

### Get User Storage
GET {{apiUrl}}/user-storage/?uid=0
Authorization: Bearer {{userAdminToken}}

### Get Notifications Storage
GET {{apiUrl}}/notification-storage/?uid=0
Authorization: Bearer {{userAdminToken}}

### Get Product Price Storage
GET {{apiUrl}}/product-price-storage/?uid=0
Authorization: Bearer {{userAdminToken}}

### Get Product Storage
GET {{apiUrl}}/product-storage/?uid=0
Authorization: Bearer {{userAdminToken}}

### Get Customer Storage
GET {{apiUrl}}/customer-storage/?uid=0
Authorization: Bearer {{userAdminToken}}

### GET Supplier Demo
GET {{apiUrl}}/supplier-storage/?uid=0
Authorization: Bearer {{userAdminToken}}
Content-Type: application/json

### GET Order Demo
GET {{apiUrl}}/order-storage/?uid=0
Authorization: Bearer {{userAdminToken}}
Content-Type: application/json
