name: Add To GitHub projects

on:
  workflow_dispatch:

  issues:
    types:
      - opened

  pull_request:
    types:
      - opened

jobs:
  add-to-project:
    name: Add To GitHub projects
    runs-on: ubuntu-latest

    steps:
      - name: Add To GitHub projects
        uses: actions/add-to-project@v0.5.0
        with:
          project-url: https://github.com/orgs/gecut/projects/1
          github-token: ${{ secrets.ADD_TO_PROJECT }}
          labeled: ci
          label-operator: NOT
